name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        r-version: "4.5.0"
    - uses: r-lib/actions/setup-r-dependencies@v2
    - uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 2
    - uses: pre-commit/action@v3.0.1
